# Generated by Django 6.1 on 2026-08-17 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KpiDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('unit', models.CharField(choices=[('count', 'Count'), ('currency', 'Currency'), ('percent', 'Percent')], default='count', max_length=16)),
                ('source_model', models.CharField(max_length=64)),
                ('aggregation', models.CharField(choices=[('count', 'Count'), ('sum', 'Sum'), ('avg', 'Average')], default='count', max_length=16)),
                ('date_field', models.CharField(default='start_at', max_length=64)),
                ('value_field', models.CharField(blank=True, default='', max_length=64)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetricFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_key', models.CharField(db_index=True, max_length=80)),
                ('bucket_date', models.DateField(db_index=True)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_facts', to='integrations.integration')),
            ],
            options={
                'indexes': [models.Index(fields=['kpi_key', 'bucket_date'], name='analytics_m_kpi_key_3dbee3_idx'), models.Index(fields=['integration', 'bucket_date'], name='analytics_m_integra_8cf51d_idx')],
                'constraints': [models.UniqueConstraint(fields=('integration', 'kpi_key', 'bucket_date', 'dimensions'), name='uniq_metric_fact')],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=160)),
                ('widget_type', models.CharField(choices=[('kpi_card', 'KPI card'), ('timeseries', 'Timeseries'), ('table', 'Table'), ('breakdown', 'Breakdown')], default='kpi_card', max_length=32)),
                ('kpi_keys', models.JSONField(blank=True, default=list)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='analytics.dashboard')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('dashboard', 'slug')},
            },
        ),
    ]
