# Generated by Django 6.1 on 2026-08-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_pricing_calculator_hub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingsubmission',
            name='num_floors',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
