# Generated by Django 6.1 on 2026-08-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_pricing_num_floors_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubemployee',
            name='attendance_days',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hubemployee',
            name='feedback_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hubemployee',
            name='late_arrivals_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hubemployee',
            name='performance_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
