# Generated by Django 6.1 on 2026-08-17 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('jobber', 'Jobber')], default='jobber', max_length=32)),
                ('account_external_id', models.CharField(blank=True, default='', max_length=128)),
                ('account_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('error', 'Error'), ('disconnected', 'Disconnected')], default='pending', max_length=24)),
                ('scopes', models.CharField(blank=True, default='', max_length=500)),
                ('access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('token_type', models.CharField(default='Bearer', max_length=32)),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'status'], name='integration_provide_c23515_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('account_external_id', ''), _negated=True), fields=('provider', 'account_external_id'), name='uniq_integration_provider_account')],
            },
        ),
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=128, unique=True)),
                ('code_verifier', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='integration_created_54f9e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='SchemaSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_version', models.CharField(max_length=32)),
                ('query_fields', models.JSONField(blank=True, default=list)),
                ('types', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_snapshots', to='integrations.integration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('full', 'Full'), ('incremental', 'Incremental')], default='full', max_length=24)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('entity_counts', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='integrations.integration')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['integration', 'status'], name='integration_integra_e0b312_idx')],
            },
        ),
    ]
