# Generated by Django 6.1 on 2026-08-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='requested_api_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='integration',
            name='served_api_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='integration',
            name='version_warning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='schemasnapshot',
            name='deprecated_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='schemasnapshot',
            name='served_api_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='schemasnapshot',
            name='versioning',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
