# Generated by Django 6.1 on 2026-08-17 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_integration_requested_api_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=64, unique=True)),
                ('topic', models.CharField(db_index=True, max_length=80)),
                ('account_id', models.CharField(db_index=True, max_length=160)),
                ('item_id', models.CharField(db_index=True, max_length=160)),
                ('app_id', models.CharField(blank=True, default='', max_length=80)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='queued', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='integrations.integration')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['topic', 'item_id', 'created_at'], name='integration_topic_77cbc4_idx'), models.Index(fields=['status', 'created_at'], name='integration_status_9b0dd1_idx')],
            },
        ),
    ]
