# Generated by Django 6.1 on 2026-08-25 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_webhookevent'),
        ('operations', '0002_widen_jobber_text_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobber_task_external_id', models.CharField(db_index=True, max_length=160)),
                ('cancellation_type', models.CharField(choices=[('cancelled_visit', 'Cancelled Visit'), ('cancelled_job', 'Cancelled Job')], db_index=True, max_length=32)),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('task_date', models.DateField(blank=True, db_index=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('division', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('is_lost_client', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-task_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('feedback_text', models.TextField(blank=True, default='')),
                ('responded', models.BooleanField(default=False)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='manual', max_length=64)),
                ('division', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('received_at', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DivisionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=120)),
                ('division', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('specialized', 'Specialized Services'), ('rentals', 'Rentals')], db_index=True, max_length=64)),
                ('priority', models.IntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'keyword'],
            },
        ),
        migrations.CreateModel(
            name='GoogleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('review_text', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateField(blank=True, db_index=True, null=True)),
                ('reply_text', models.TextField(blank=True, default='')),
                ('replied', models.BooleanField(default=False)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-reviewed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JobberTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=160)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('instructions', models.TextField(blank=True, default='')),
                ('task_status', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTypeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=120)),
                ('service_type', models.CharField(db_index=True, max_length=120)),
                ('priority', models.IntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'keyword'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='average_price_per_visit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='division',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='client',
            name='monthly_recurring_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='division',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='job',
            name='monthly_recurring_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='service_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='job',
            name='team_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_jobs', to='operations.employee'),
        ),
        migrations.AddField(
            model_name='visit',
            name='division',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='visit',
            name='service_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='visit',
            name='team_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_visits', to='operations.employee'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['division'], name='operations__divisio_4aeec4_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['division', 'service_type'], name='operations__divisio_6b6afc_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['division', 'service_type'], name='operations__divisio_871e34_idx'),
        ),
        migrations.AddField(
            model_name='cancellationrecord',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellations', to='operations.client'),
        ),
        migrations.AddField(
            model_name='cancellationrecord',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='integrations.integration'),
        ),
        migrations.AddField(
            model_name='cancellationrecord',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellations', to='operations.job'),
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='operations.client'),
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='integrations.integration'),
        ),
        migrations.AddField(
            model_name='jobbertask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='operations.employee'),
        ),
        migrations.AddField(
            model_name='jobbertask',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='operations.client'),
        ),
        migrations.AddField(
            model_name='jobbertask',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.integration'),
        ),
        migrations.AddField(
            model_name='jobbertask',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='operations.job'),
        ),
        migrations.AddField(
            model_name='cancellationrecord',
            name='jobber_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellation', to='operations.jobbertask'),
        ),
        migrations.AddIndex(
            model_name='jobbertask',
            index=models.Index(fields=['title'], name='operations__title_117eb3_idx'),
        ),
        migrations.AddIndex(
            model_name='jobbertask',
            index=models.Index(fields=['due_at'], name='operations__due_at_d891ea_idx'),
        ),
        migrations.AddIndex(
            model_name='jobbertask',
            index=models.Index(fields=['task_status'], name='operations__task_st_c52de5_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobbertask',
            constraint=models.UniqueConstraint(fields=('integration', 'external_id'), name='uniq_jobber_task_ext'),
        ),
        migrations.AddIndex(
            model_name='cancellationrecord',
            index=models.Index(fields=['cancellation_type', 'task_date'], name='operations__cancell_17509f_idx'),
        ),
        migrations.AddIndex(
            model_name='cancellationrecord',
            index=models.Index(fields=['division', 'cancellation_type'], name='operations__divisio_9226b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='cancellationrecord',
            constraint=models.UniqueConstraint(fields=('integration', 'jobber_task_external_id'), name='uniq_cancellation_task'),
        ),
    ]
